import React, { useState, useEffect } from 'react';
import { useLocation, Link } from 'react-router-dom';
import { ShieldCheck, FileText, RefreshCcw, Truck, Mail, ArrowRight } from 'lucide-react';

const policies = [
  {
    id: 'terms',
    name: 'Terms & Conditions',
    icon: FileText,
    title: 'Terms of Service & Usage',
    updatedAt: 'September 2026',
    content: (
      <div className="space-y-4 text-sm text-[#475569] leading-relaxed">
        <p>
          Welcome to <strong>SOWMYA.KCODE</strong> (https://sowmya-kcode.com). By purchasing or accessing our DSA Demystified Notes, you agree to comply with and be bound by the following terms and conditions.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">1. Intellectual Property & License</h3>
        <p>
          All content, visual mental models, code snippets (in Java, C++, Python), problem walkthroughs, and PDFs provided on this website are the proprietary intellectual property of <strong>Sowmya Katkojwal (@sowmya.kcode)</strong>.
        </p>
        <p>
          Your purchase grants you a single-user, non-exclusive, non-transferable lifetime personal license to download, read, and study the DSA Notes. Redistribution, resale, public sharing, uploading to third-party file hosts or Telegram groups, or reproduction without express written consent is strictly prohibited.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">2. Digital Product Purchase</h3>
        <p>
          The product offered is an electronic digital download (PDF format) titled <em>"DSA Demystified (Phone-First Master Edition)"</em> at the stated price of <strong>₹39 (inclusive of all applicable taxes)</strong>.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">3. Account Responsibility</h3>
        <p>
          You are responsible for maintaining the confidentiality of your account credentials and token. You agree to notify us immediately at <strong>sowmyaKatkojwal@gmail.com</strong> if you suspect any unauthorized access to your account.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">4. Modification of Services</h3>
        <p>
          We reserve the right to periodically update, enhance, or revise the course materials to keep them relevant with current technical interview standards. All registered buyers receive lifetime access to revised editions at no additional charge.
        </p>
      </div>
    ),
  },
  {
    id: 'privacy',
    name: 'Privacy Policy',
    icon: ShieldCheck,
    title: 'Privacy & Data Protection Policy',
    updatedAt: 'September 2026',
    content: (
      <div className="space-y-4 text-sm text-[#475569] leading-relaxed">
        <p>
          At <strong>SOWMYA.KCODE</strong>, we respect your privacy and are committed to protecting your personal information. This Privacy Policy outlines how your information is collected, used, and secured.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">1. Information We Collect</h3>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong>Personal Details:</strong> Name, email address, and optional phone number provided during registration or checkout.</li>
          <li><strong>Transaction Metadata:</strong> Order ID, payment verification reference, and timestamp generated by Razorpay. We <strong>never</strong> store or access your bank PINs, UPI MPIN, passwords, or full credit/debit card numbers.</li>
          <li><strong>Device & Access Logs:</strong> IP address and user-agent recorded solely for download authentication and preventing digital piracy.</li>
        </ul>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">2. How We Use Your Data</h3>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>To authenticate and unlock your digital PDF download access.</li>
          <li>To email your official purchase confirmation and payment receipt.</li>
          <li>To provide customer support and notify you of free future roadmap updates.</li>
        </ul>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">3. Third-Party Payment Gateway</h3>
        <p>
          All monetary transactions are processed securely through <strong>Razorpay Payment Gateway</strong>, which adheres strictly to PCI-DSS Level 1 compliance and 256-bit SSL bank-grade encryption.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">4. Data Sharing & Retention</h3>
        <p>
          We do not sell, rent, or trade your personal data to any third-party advertisers. Your information is retained solely to facilitate your lifetime download access.
        </p>
      </div>
    ),
  },
  {
    id: 'refund',
    name: 'Refund Policy',
    icon: RefreshCcw,
    title: 'Cancellation & Refund Policy',
    updatedAt: 'September 2026',
    content: (
      <div className="space-y-4 text-sm text-[#475569] leading-relaxed">
        <p>
          Thank you for investing in the <strong>DSA Demystified Notes</strong> by Sowmya Katkojwal. Please read our cancellation and refund guidelines carefully.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">1. Nature of the Product</h3>
        <p>
          Because <em>DSA Demystified</em> is an instantly downloadable digital PDF product, once the payment is completed and download access is delivered, the digital asset cannot be returned. Therefore, purchases are generally non-refundable once downloaded.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">2. Duplicate Charges / Erroneous Debits</h3>
        <p>
          If your account was debited multiple times due to a network glitch or if you were charged without receiving order confirmation:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Send an email to <strong>sowmyaKatkojwal@gmail.com</strong> with your payment ID and date of transaction.</li>
          <li>Once verified via Razorpay records, any duplicate charge will be refunded back to your original payment method within <strong>5–7 business days</strong>.</li>
        </ul>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">3. Access Resolution Guarantee</h3>
        <p>
          If you encounter any technical difficulty downloading or viewing your PDF notes after payment, our support team will resolve it within 24 hours or send a direct authenticated copy to your registered email address.
        </p>
      </div>
    ),
  },
  {
    id: 'shipping',
    name: 'Shipping & Delivery',
    icon: Truck,
    title: 'Digital Delivery Policy',
    updatedAt: 'September 2026',
    content: (
      <div className="space-y-4 text-sm text-[#475569] leading-relaxed">
        <p>
          <strong>SOWMYA.KCODE</strong> exclusively provides electronic digital learning materials. No physical items, books, or parcels are shipped via post or courier.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">1. Delivery Timeline: Instant Electronic Delivery</h3>
        <p>
          Delivery of your purchased notes is <strong>100% electronic and instantaneous</strong>.
        </p>
        <p>
          Immediately upon successful Razorpay payment confirmation (usually within 1–5 seconds), your account is automatically unlocked and:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>A direct <strong>"Download DSA Notes PDF"</strong> button appears on your screen.</li>
          <li>The notes become permanently accessible in your <strong>Student Dashboard</strong> under the "My Notes" and "Downloads" sections.</li>
        </ul>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">2. Shipping Charges</h3>
        <p>
          Because delivery is digital, <strong>shipping charges are ₹0 (FREE)</strong> across all states in India and worldwide.
        </p>

        <h3 className="text-base font-bold text-[#0F172A] pt-2">3. Delivery Inquiries</h3>
        <p>
          If you did not receive immediate download access after paying, please email your Razorpay Payment ID to <strong>sowmyaKatkojwal@gmail.com</strong> for instant manual assistance.
        </p>
      </div>
    ),
  },
];

const PoliciesPage = () => {
  const location = useLocation();
  const [activeTab, setActiveTab] = useState('terms');

  useEffect(() => {
    const path = location.pathname.replace('/', '').toLowerCase();
    if (['terms', 'privacy', 'refund', 'shipping'].includes(path)) {
      setActiveTab(path);
    }
  }, [location.pathname]);

  const activePolicy = policies.find((p) => p.id === activeTab) || policies[0];
  const Icon = activePolicy.icon;

  return (
    <div className="min-h-screen pt-28 pb-20 bg-[#F8FBFF]">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header */}
        <div className="text-center mb-10">
          <span className="text-cyan-600 font-bold text-xs uppercase tracking-wider bg-cyan-50 px-3 py-1 rounded-full border border-cyan-100 inline-block mb-2">
            Compliance & Transparency
          </span>
          <h1 className="text-3xl sm:text-4xl font-black text-[#0F172A] tracking-tight">
            Legal & Customer Policies
          </h1>
          <p className="text-xs sm:text-sm text-[#475569] mt-2">
            Clear, transparent policies for the SOWMYA.KCODE DSA Notes platform.
          </p>
        </div>

        {/* Tab Selector */}
        <div className="flex items-center justify-center gap-2 flex-wrap mb-8">
          {policies.map((p) => (
            <button
              key={p.id}
              onClick={() => setActiveTab(p.id)}
              className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-bold transition cursor-pointer flex items-center gap-1.5 ${
                activeTab === p.id
                  ? 'bg-cyan-600 text-white shadow-md shadow-cyan-500/20'
                  : 'bg-white text-slate-600 border border-slate-200 hover:border-cyan-200 hover:text-cyan-700'
              }`}
            >
              <p.icon size={15} />
              <span>{p.name}</span>
            </button>
          ))}
        </div>

        {/* Policy Content Card */}
        <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-10 shadow-xs space-y-6">
          <div className="border-b border-slate-100 pb-4 flex items-center justify-between flex-wrap gap-2">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-cyan-50 text-cyan-600 border border-cyan-100 flex items-center justify-center">
                <Icon size={20} />
              </div>
              <div>
                <h2 className="text-xl font-black text-[#0F172A]">{activePolicy.title}</h2>
                <p className="text-xs text-slate-400">Last updated: {activePolicy.updatedAt}</p>
              </div>
            </div>
            <span className="text-[11px] font-bold text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
              Active Policy
            </span>
          </div>

          {activePolicy.content}

          {/* Contact Support Note */}
          <div className="mt-8 pt-6 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-500 bg-slate-50/50 p-4 rounded-2xl">
            <div className="flex items-center gap-2">
              <Mail size={16} className="text-cyan-600 shrink-0" />
              <span>Have policy questions? Email <strong>sowmyaKatkojwal@gmail.com</strong></span>
            </div>
            <Link
              to="/contact"
              className="text-cyan-700 font-bold hover:underline flex items-center gap-1 shrink-0"
            >
              <span>Contact Page</span>
              <ArrowRight size={13} />
            </Link>
          </div>
        </div>

      </div>
    </div>
  );
};

export default PoliciesPage;
